version: '3'

services:
  db:
    image: mdillon/postgis:11-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: django_polls
      POSTGRES_DB: django_polls
      POSTGRES_PASSWORD: django_polls
