# Generated by Django 3.0.8 on 2020-09-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="poll",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
