# Generated by Django 3.0.8 on 2020-09-21 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0002_auto_20200921_1442"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={"verbose_name": "выбор", "verbose_name_plural": "выборы"},
        ),
        migrations.AlterModelOptions(
            name="poll",
            options={"verbose_name": "опрос", "verbose_name_plural": "опросы"},
        ),
        migrations.AlterModelOptions(
            name="vote",
            options={"verbose_name": "голос", "verbose_name_plural": "голоса"},
        ),
        migrations.AlterField(
            model_name="choice",
            name="choice_text",
            field=models.CharField(max_length=100, verbose_name="Выбор"),
        ),
        migrations.AlterField(
            model_name="choice",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="polls.Poll",
                verbose_name="Опрос",
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="description",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата оканчания"
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="pub_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="poll",
            name="question",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
    ]
