# Generated by Django 3.0.8 on 2020-09-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_auto_20200921_1750"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poll",
            old_name="question",
            new_name="title",
        ),
    ]
